<?php
declare(strict_types=1);

/**
 * Tithika route map.
 * Each route is a logical page. Shared rendering prevents duplicated markup while
 * preserving a stable, crawlable URL for every mapped product surface.
 */
return [
    'panchang' => [
        'title' => 'Panchang',
        'icon' => '☸',
        'description' => 'Daily, monthly and regional Panchang experiences with location-aware solar context.',
        'pages' => [
            ['slug'=>'panchang/month','title'=>'Month Panchang','template'=>'calendar'],
            ['slug'=>'panchang/daily','title'=>'Dainik Panchang','template'=>'daily'],
            ['slug'=>'panchang/hindi','title'=>'Hindi Panchang','template'=>'calendar'],
            ['slug'=>'panchang/tamil','title'=>'Tamil Panchangam','template'=>'calendar'],
            ['slug'=>'panchang/telugu','title'=>'Telugu Panchangam','template'=>'calendar'],
            ['slug'=>'panchang/kannada','title'=>'Kannada Panchang','template'=>'calendar'],
            ['slug'=>'panchang/malayalam','title'=>'Malayalam Panchangam','template'=>'calendar'],
            ['slug'=>'panchang/gujarati','title'=>'Gujarati Panchang','template'=>'calendar'],
            ['slug'=>'panchang/marathi','title'=>'Marathi Panchang','template'=>'calendar'],
            ['slug'=>'panchang/bengali','title'=>'Bengali Panjika','template'=>'calendar'],
            ['slug'=>'panchang/odia','title'=>'Odia Panji','template'=>'calendar'],
            ['slug'=>'panchang/nepali','title'=>'Nepali Patro','template'=>'calendar'],
            ['slug'=>'panchang/iskcon','title'=>'ISKCON Panchang','template'=>'calendar'],
            ['slug'=>'panchang/assamese','title'=>'Assamese Panjika','template'=>'calendar'],
            ['slug'=>'panchang/gowri','title'=>'Gowri Panchangam','template'=>'muhurat'],
            ['slug'=>'panchang/published','title'=>'Published Panchang','template'=>'article'],
            ['slug'=>'panchang/sunrise','title'=>'Hindu Sunrise','template'=>'daily'],
            ['slug'=>'panchang/rahu-kala','title'=>'Rahu Kala','template'=>'muhurat'],
            ['slug'=>'panchang/abhijit-nakshatra','title'=>'Abhijit Nakshatra','template'=>'list'],
            ['slug'=>'panchang/panchak','title'=>'Panchak','template'=>'list'],
            ['slug'=>'panchang/bhadra','title'=>'Bhadra Vichar','template'=>'list'],
            ['slug'=>'panchang/ganda-moola','title'=>'Ganda Moola','template'=>'list'],
            ['slug'=>'panchang/manvadi-tithi','title'=>'Manvadi Tithi','template'=>'list'],
            ['slug'=>'panchang/yugadi-tithi','title'=>'Yugadi Tithi','template'=>'list'],
            ['slug'=>'panchang/kalpadi-tithi','title'=>'Kalpadi Tithi','template'=>'list'],
            ['slug'=>'panchang/vinchudo','title'=>'Vinchudo','template'=>'list'],
            ['slug'=>'panchang/kranti-samya','title'=>'Kranti Samya Dosha','template'=>'list'],
            ['slug'=>'panchang/jwalamukhi-yoga','title'=>'Jwalamukhi Yoga','template'=>'list'],
            ['slug'=>'panchang/chandrabalam','title'=>'Chandrabalam','template'=>'calculator'],
            ['slug'=>'panchang/tarabalam','title'=>'Tarabalam','template'=>'calculator'],
            ['slug'=>'panchang/sankalpa','title'=>'Sankalpa','template'=>'calculator'],
            ['slug'=>'panchang/nakshatra','title'=>'Nakshatra','template'=>'list'],
            ['slug'=>'panchang/utilities','title'=>'Panchang Utilities','template'=>'collection'],
            ['slug'=>'panchang/lagna-kundali','title'=>'Lagna Kundali','template'=>'astronomy'],
            ['slug'=>'panchang/vedic-clock','title'=>'Vedic Clock','template'=>'daily'],
            ['slug'=>'panchang/moonrise-moonset','title'=>'Moonrise & Moonset','template'=>'daily'],
        ]
    ],
    'calendars' => [
        'title' => 'Calendars',
        'icon' => '▦',
        'description' => 'Regional, festival and yearly Vedic calendar views.',
        'pages' => [
            ['slug'=>'calendars/hindu','title'=>'Hindu Calendar','template'=>'calendar'],
            ['slug'=>'calendars/indian','title'=>'Indian Calendar','template'=>'calendar'],
            ['slug'=>'calendars/tamil','title'=>'Tamil Calendar','template'=>'calendar'],
            ['slug'=>'calendars/telugu','title'=>'Telugu Calendar','template'=>'calendar'],
            ['slug'=>'calendars/kannada','title'=>'Kannada Calendar','template'=>'calendar'],
            ['slug'=>'calendars/malayalam','title'=>'Malayalam Calendar','template'=>'calendar'],
            ['slug'=>'calendars/gujarati','title'=>'Gujarati Calendar','template'=>'calendar'],
            ['slug'=>'calendars/marathi','title'=>'Marathi Calendar','template'=>'calendar'],
            ['slug'=>'calendars/bengali','title'=>'Bengali Calendar','template'=>'calendar'],
            ['slug'=>'calendars/odia','title'=>'Odia Calendar','template'=>'calendar'],
            ['slug'=>'calendars/jain','title'=>'Jain Calendar','template'=>'calendar'],
            ['slug'=>'calendars/iskcon','title'=>'ISKCON Calendar','template'=>'calendar'],
            ['slug'=>'calendars/assamese','title'=>'Assamese Calendar','template'=>'calendar'],
            ['slug'=>'calendars/diwali','title'=>'Diwali Puja Calendar','template'=>'festival'],
            ['slug'=>'calendars/durga-puja','title'=>'Durga Puja Calendar','template'=>'festival'],
            ['slug'=>'calendars/onam','title'=>'Onam Calendar','template'=>'festival'],
            ['slug'=>'calendars/mysore-dasara','title'=>'Mysore Dasara Calendar','template'=>'festival'],
            ['slug'=>'calendars/saraswati-puja','title'=>'Saraswati Puja Calendar','template'=>'festival'],
            ['slug'=>'calendars/chhath','title'=>'Chhath Puja Calendar','template'=>'festival'],
            ['slug'=>'calendars/navratri','title'=>'Navratri Calendar','template'=>'festival'],
            ['slug'=>'calendars/shardiya-navratri','title'=>'Shardiya Navratri','template'=>'festival'],
            ['slug'=>'calendars/chaitra-navratri','title'=>'Chaitra Navratri','template'=>'festival'],
            ['slug'=>'calendars/sankranti','title'=>'Makar Sankranti Calendar','template'=>'festival'],
            ['slug'=>'calendars/dashavatara','title'=>'Dashavatara Calendar','template'=>'festival'],
            ['slug'=>'calendars/dasha-mahavidya','title'=>'Dasha Mahavidya','template'=>'festival'],
            ['slug'=>'calendars/dwadasha-siddhividya','title'=>'Dwadasha Siddhividya','template'=>'festival'],
            ['slug'=>'calendars/gujarati-diwali','title'=>'Gujarati Diwali Calendar','template'=>'festival'],
            ['slug'=>'calendars/purnima','title'=>'Purnima Calendar','template'=>'calendar'],
            ['slug'=>'calendars/nepali','title'=>'Nepali Calendar','template'=>'calendar'],
            ['slug'=>'calendars/dashain','title'=>'Dashain Calendar','template'=>'festival'],
            ['slug'=>'calendars/tihar','title'=>'Tihar Calendar','template'=>'festival'],
        ]
    ],
    'muhurat' => [
        'title' => 'Muhurat',
        'icon' => '✦',
        'description' => 'Daily and ceremony-specific auspicious timing utilities.',
        'pages' => [
            ['slug'=>'muhurat/choghadiya','title'=>'Choghadiya Muhurat','template'=>'muhurat','live'=>'choghadiya.php'],
            ['slug'=>'muhurat/shubha-hora','title'=>'Shubha Hora','template'=>'muhurat'],
            ['slug'=>'muhurat/vivah','title'=>'Vivah Muhurat','template'=>'muhurat'],
            ['slug'=>'muhurat/griha-pravesh','title'=>'Griha Pravesh','template'=>'muhurat'],
            ['slug'=>'muhurat/property','title'=>'Property Purchase','template'=>'muhurat'],
            ['slug'=>'muhurat/vehicle','title'=>'Vehicle Purchase','template'=>'muhurat'],
            ['slug'=>'muhurat/lagna','title'=>'Lagna Muhurat','template'=>'muhurat'],
            ['slug'=>'muhurat/gowri','title'=>'Gowri Panchangam','template'=>'muhurat'],
            ['slug'=>'muhurat/jain-pachchakkhan','title'=>'Jain Pachchakkhan','template'=>'muhurat'],
            ['slug'=>'muhurat/rahu-kala','title'=>'Rahu Kala','template'=>'muhurat'],
            ['slug'=>'muhurat/auspicious-yoga','title'=>'Auspicious Yogas','template'=>'list'],
            ['slug'=>'muhurat/panchaka-rahita','title'=>'Panchaka Rahita Muhurat','template'=>'muhurat'],
            ['slug'=>'muhurat/abhijit','title'=>'Abhijit Muhurat','template'=>'muhurat'],
            ['slug'=>'muhurat/do-ghati','title'=>'Do Ghati Muhurat','template'=>'muhurat'],
            ['slug'=>'muhurat/shubha-dates','title'=>'Shubha Dates','template'=>'calendar'],
            ['slug'=>'muhurat/pancha-pakshi','title'=>'Pancha Pakshi Activities','template'=>'calculator'],
            ['slug'=>'muhurat/guru-pushya','title'=>'Guru Pushya Yoga','template'=>'calendar'],
            ['slug'=>'muhurat/sarvartha-siddhi','title'=>'Sarvartha Siddhi Yoga','template'=>'calendar'],
            ['slug'=>'muhurat/amrit-siddhi','title'=>'Amrit Siddhi Yoga','template'=>'calendar'],
            ['slug'=>'muhurat/dwipushkar','title'=>'Dwipushkar Yoga','template'=>'calendar'],
            ['slug'=>'muhurat/tripushkar','title'=>'Tripushkar Yoga','template'=>'calendar'],
            ['slug'=>'muhurat/ravi-pushya','title'=>'Ravi Pushya Yoga','template'=>'calendar'],
            ['slug'=>'muhurat/ravi-yoga','title'=>'Ravi Yoga','template'=>'calendar'],
        ]
    ],
    'vrat' => [
        'title' => 'Vrat & Upavas',
        'icon' => '◐',
        'description' => 'Fasting dates, Parana windows and recurring observance calendars.',
        'pages' => [
            ['slug'=>'vrat/top-10','title'=>'Top 10 Hindu Vrats','template'=>'collection'],
            ['slug'=>'vrat/sankashti-chaturthi','title'=>'Sankashti Chaturthi','template'=>'calendar'],
            ['slug'=>'vrat/ekadashi','title'=>'Ekadashi Dates','template'=>'calendar'],
            ['slug'=>'vrat/pradosham','title'=>'Pradosham Dates','template'=>'calendar'],
            ['slug'=>'vrat/vinayaka-chaturthi','title'=>'Vinayaka Chaturthi','template'=>'calendar'],
            ['slug'=>'vrat/dwadashi','title'=>'Dwadashi Dates','template'=>'calendar'],
            ['slug'=>'vrat/mahadwadashi','title'=>'Mahadwadashi','template'=>'calendar'],
            ['slug'=>'vrat/masik-shivaratri','title'=>'Masik Shivaratri','template'=>'calendar'],
            ['slug'=>'vrat/sawan-somwar','title'=>'Sawan Somwar','template'=>'calendar'],
            ['slug'=>'vrat/satyanarayana','title'=>'Satyanarayana Puja','template'=>'calendar'],
            ['slug'=>'vrat/purnima','title'=>'Purnima Vrat','template'=>'calendar'],
            ['slug'=>'vrat/navagraha-weekdays','title'=>'Navagraha Weekday Fasting','template'=>'collection'],
            ['slug'=>'vrat/deity-weekdays','title'=>'Deity Weekday Fasting','template'=>'collection'],
            ['slug'=>'vrat/amavasya','title'=>'Amavasya Dates','template'=>'calendar'],
            ['slug'=>'vrat/skanda-sashti','title'=>'Skanda Sashti','template'=>'calendar'],
            ['slug'=>'vrat/karthigai','title'=>'Karthigai Days','template'=>'calendar'],
            ['slug'=>'vrat/shraddha','title'=>'Shraddha Dates','template'=>'calendar'],
            ['slug'=>'vrat/durgashtami','title'=>'Durgashtami Days','template'=>'calendar'],
            ['slug'=>'vrat/kalashtami','title'=>'Kalashtami Days','template'=>'calendar'],
            ['slug'=>'vrat/rohini','title'=>'Rohini Vrat','template'=>'calendar'],
            ['slug'=>'vrat/sankranti','title'=>'Sankranti Dates','template'=>'calendar'],
            ['slug'=>'vrat/chandra-darshan','title'=>'Chandra Darshan','template'=>'calendar'],
            ['slug'=>'vrat/mangala-gauri','title'=>'Mangala Gauri','template'=>'calendar'],
            ['slug'=>'vrat/ishti-anvadhan','title'=>'Ishti & Anvadhan','template'=>'calendar'],
            ['slug'=>'vrat/iskcon-ekadashi','title'=>'ISKCON Ekadashi','template'=>'calendar'],
            ['slug'=>'vrat/masik-janmashtami','title'=>'Masik Krishna Janmashtami','template'=>'calendar'],
            ['slug'=>'vrat/dashavatara','title'=>'Dashavatara Vrat','template'=>'calendar'],
            ['slug'=>'vrat/purushottam-maas','title'=>'Purushottam Maas','template'=>'calendar'],
            ['slug'=>'vrat/chaturmasa','title'=>'Chaturmasa','template'=>'calendar'],
            ['slug'=>'vrat/ashoka-ashtami','title'=>'Ashoka Ashtami','template'=>'calendar'],
            ['slug'=>'vrat/asha-dashami','title'=>'Asha Dashami','template'=>'calendar'],
            ['slug'=>'vrat/durva-ashtami','title'=>'Durva Ashtami','template'=>'calendar'],
            ['slug'=>'vrat/jivit-putrika','title'=>'Jivit Putrika Vrat','template'=>'calendar'],
            ['slug'=>'vrat/shitala-saptami','title'=>'Shitala Saptami','template'=>'calendar'],
            ['slug'=>'vrat/katha','title'=>'Vrat Katha','template'=>'article'],
            ['slug'=>'vrat/katha/satyanarayana','title'=>'Satyanarayana Vrat Katha','template'=>'article'],
            ['slug'=>'vrat/katha/ekadashi','title'=>'Ekadashi Vrat Katha','template'=>'article'],
            ['slug'=>'vrat/katha/karwa-chauth','title'=>'Karwa Chauth Vrat Katha','template'=>'article'],
            ['slug'=>'vrat/katha/ahoi-ashtami','title'=>'Ahoi Ashtami Vrat Katha','template'=>'article'],
        ]
    ],
    'festivals' => [
        'title' => 'Festivals',
        'icon' => '🪷',
        'description' => 'Festival collections, month views, deity traditions and observance guides.',
        'pages' => [
            ['slug'=>'festivals/top-10','title'=>'Top 10 Hindu Festivals','template'=>'collection'],
            ['slug'=>'festivals/top-20','title'=>'Top 20 Hindu Festivals','template'=>'collection'],
            ['slug'=>'festivals/top-25','title'=>'Top 25 Hindu Festivals','template'=>'collection'],
            ['slug'=>'festivals/hindu','title'=>'Hindu Festivals','template'=>'festival'],
            ['slug'=>'festivals/tamil','title'=>'Tamil Festivals','template'=>'festival'],
            ['slug'=>'festivals/malayalam','title'=>'Malayalam Festivals','template'=>'festival'],
            ['slug'=>'festivals/sankranti','title'=>'Sankranti Festivals','template'=>'festival'],
            ['slug'=>'festivals/gurus-saints','title'=>'Gurus and Saints','template'=>'collection'],
            ['slug'=>'festivals/chaitra','title'=>'Chaitra Festivals','template'=>'festival'],
            ['slug'=>'festivals/vaishakha','title'=>'Vaishakha Festivals','template'=>'festival'],
            ['slug'=>'festivals/jyeshtha','title'=>'Jyeshtha Festivals','template'=>'festival'],
            ['slug'=>'festivals/ashadha','title'=>'Ashadha Festivals','template'=>'festival'],
            ['slug'=>'festivals/shravana','title'=>'Shravana Festivals','template'=>'festival'],
            ['slug'=>'festivals/bhadrapada','title'=>'Bhadrapada Festivals','template'=>'festival'],
            ['slug'=>'festivals/ashwina','title'=>'Ashwina Festivals','template'=>'festival'],
            ['slug'=>'festivals/kartika','title'=>'Kartika Festivals','template'=>'festival'],
            ['slug'=>'festivals/margashirsha','title'=>'Margashirsha Festivals','template'=>'festival'],
            ['slug'=>'festivals/pausha','title'=>'Pausha Festivals','template'=>'festival'],
            ['slug'=>'festivals/magha','title'=>'Magha Festivals','template'=>'festival'],
            ['slug'=>'festivals/phalguna','title'=>'Phalguna Festivals','template'=>'festival'],
            ['slug'=>'festivals/dashavatara','title'=>'Dashavatara','template'=>'article'],
            ['slug'=>'festivals/navdurga','title'=>'Navdurga','template'=>'article'],
            ['slug'=>'festivals/puja-vidhi','title'=>'Puja Vidhi','template'=>'collection'],
            ['slug'=>'festivals/deities','title'=>'Hindu Deities','template'=>'collection'],
            ['slug'=>'festivals/regional-deities','title'=>'Regional Deities','template'=>'collection'],
            ['slug'=>'festivals/pilgrim-places','title'=>'Hindu Pilgrim Places','template'=>'collection'],
            ['slug'=>'festivals/vishnu-avatars','title'=>'24 Vishnu Avatara','template'=>'article'],
            ['slug'=>'festivals/diwali','title'=>'Diwali','template'=>'festival'],
            ['slug'=>'festivals/raksha-bandhan','title'=>'Raksha Bandhan','template'=>'festival'],
            ['slug'=>'festivals/maha-shivaratri','title'=>'Maha Shivaratri','template'=>'festival'],
            ['slug'=>'festivals/holi','title'=>'Holi','template'=>'festival'],
            ['slug'=>'festivals/ganesha-chaturthi','title'=>'Ganesha Chaturthi','template'=>'festival'],
            ['slug'=>'festivals/durga-puja','title'=>'Durga Puja','template'=>'festival'],
            ['slug'=>'festivals/navratri','title'=>'Navratri','template'=>'festival'],
            ['slug'=>'festivals/dussehra','title'=>'Dussehra','template'=>'festival'],
            ['slug'=>'festivals/makar-sankranti','title'=>'Makar Sankranti','template'=>'festival'],
            ['slug'=>'festivals/karwa-chauth','title'=>'Karwa Chauth','template'=>'festival'],
            ['slug'=>'festivals/janmashtami','title'=>'Janmashtami','template'=>'festival'],
            ['slug'=>'festivals/rama-navami','title'=>'Rama Navami','template'=>'festival'],
            ['slug'=>'festivals/hanuman-jayanti','title'=>'Hanuman Jayanti','template'=>'festival'],
            ['slug'=>'festivals/akshaya-tritiya','title'=>'Akshaya Tritiya','template'=>'festival'],
            ['slug'=>'festivals/vat-savitri','title'=>'Vat Savitri Vrat','template'=>'festival'],
            ['slug'=>'festivals/puja/ganesha','title'=>'Ganesha Puja Vidhi','template'=>'article'],
            ['slug'=>'festivals/puja/lakshmi','title'=>'Lakshmi Puja Vidhi','template'=>'article'],
            ['slug'=>'festivals/puja/shivaratri','title'=>'Shivaratri Puja Vidhi','template'=>'article'],
            ['slug'=>'festivals/puja/holi','title'=>'Holi Puja Vidhi','template'=>'article'],
        ]
    ],
    'jyotish' => [
        'title' => 'Jyotish',
        'icon' => '◎',
        'description' => 'Birth, compatibility and traditional Jyotish calculators in focused flows.',
        'pages' => [
            ['slug'=>'jyotish/prashna-kundali','title'=>'Prashna Kundali','template'=>'calculator'],
            ['slug'=>'jyotish/janma-kundali','title'=>'Janma Kundali','template'=>'calculator'],
            ['slug'=>'jyotish/vimshottari-dasha','title'=>'Vimshottari Dasha','template'=>'calculator'],
            ['slug'=>'jyotish/ashtakavarga','title'=>'Ashtakavarga','template'=>'calculator'],
            ['slug'=>'jyotish/shadbala','title'=>'Shadbala Strength Foundation','template'=>'calculator'],
            ['slug'=>'jyotish/pancha-pakshi','title'=>'Pancha Pakshi Bird Calculator','template'=>'calculator'],
            ['slug'=>'jyotish/gemstone','title'=>'Gemstone Calculator','template'=>'calculator'],
            ['slug'=>'jyotish/rudraksha','title'=>'Rudraksha Calculator','template'=>'calculator'],
            ['slug'=>'jyotish/kalasarpa','title'=>'Kalasarpa Yoga Calculator','template'=>'calculator'],
            ['slug'=>'jyotish/shani-sadesati','title'=>'Shani Sadesati Calculator','template'=>'calculator'],
            ['slug'=>'jyotish/baby-name','title'=>'Baby Name Calculator','template'=>'calculator'],
            ['slug'=>'jyotish/horoscope-match','title'=>'Horoscope Matching','template'=>'calculator'],
            ['slug'=>'jyotish/marriage-analysis','title'=>'Deep Marriage Analysis','template'=>'calculator'],
            ['slug'=>'jyotish/nakshatra-compatibility','title'=>'Nakshatra Compatibility','template'=>'calculator'],
            ['slug'=>'jyotish/moonsign','title'=>'Janmarashi Calculator','template'=>'calculator'],
            ['slug'=>'jyotish/rashifal','title'=>'Vedic Rashifal','template'=>'list'],
            ['slug'=>'jyotish/birthstar','title'=>'Birthstar Calculator','template'=>'calculator'],
            ['slug'=>'jyotish/janma-lagna','title'=>'Janma Lagna Calculator','template'=>'calculator'],
            ['slug'=>'jyotish/sunsign','title'=>'Surya Rashi Calculator','template'=>'calculator'],
            ['slug'=>'jyotish/mangal-dosha','title'=>'Mangal Dosha Calculator','template'=>'calculator'],
            ['slug'=>'jyotish/sahasra-chandrodaya','title'=>'1000 Chandrodaya Calculator','template'=>'calculator'],
            ['slug'=>'jyotish/vedic-time','title'=>'Vedic Time','template'=>'daily'],
            ['slug'=>'jyotish/shraddha-tithi','title'=>'Shraddha Tithi Calculator','template'=>'calculator'],
            ['slug'=>'jyotish/name-initials','title'=>'Name Initials','template'=>'calculator'],
            ['slug'=>'jyotish/prashnavali','title'=>'Prashnavali','template'=>'calculator'],
            ['slug'=>'jyotish/rashifal/daily','title'=>'Daily Rashifal','template'=>'list'],
            ['slug'=>'jyotish/rashifal/weekly','title'=>'Weekly Rashifal','template'=>'list'],
            ['slug'=>'jyotish/rashifal/monthly','title'=>'Monthly Rashifal','template'=>'list'],
            ['slug'=>'jyotish/rashifal/yearly','title'=>'Yearly Rashifal','template'=>'list'],
            ['slug'=>'jyotish/rashi-by-name','title'=>'Find Rashi by Name','template'=>'calculator'],
        ]
    ],
    'planets' => [
        'title' => 'Planets & Astronomy',
        'icon' => '◉',
        'description' => 'Planetary positions, transits, aspects, eclipses and seasonal astronomy.',
        'pages' => [
            ['slug'=>'planets/positions','title'=>'Planetary Positions','template'=>'astronomy'],
            ['slug'=>'planets/transit','title'=>'Planet Transit','template'=>'astronomy'],
            ['slug'=>'planets/combustion','title'=>'Planet Combustion','template'=>'astronomy'],
            ['slug'=>'planets/retrograde','title'=>'Planet Retrograde','template'=>'astronomy'],
            ['slug'=>'planets/mutual-aspects','title'=>'Planets Mutual Aspects','template'=>'astronomy'],
            ['slug'=>'planets/conjunctions','title'=>'Planet Conjunctions','template'=>'astronomy'],
            ['slug'=>'planets/lunar-aspects','title'=>'Lunar Aspects','template'=>'astronomy'],
            ['slug'=>'planets/parallel','title'=>'Planets Mutual Parallel','template'=>'astronomy'],
            ['slug'=>'planets/ecliptic-crossings','title'=>'Planets Ecliptic Crossings','template'=>'astronomy'],
            ['slug'=>'planets/graha-yuddha','title'=>'Graha Yuddha','template'=>'astronomy'],
            ['slug'=>'astronomy/eclipses','title'=>'Eclipse Dates','template'=>'astronomy'],
            ['slug'=>'astronomy/solar-eclipse','title'=>'Solar Eclipse','template'=>'astronomy'],
            ['slug'=>'astronomy/lunar-eclipse','title'=>'Lunar Eclipse','template'=>'astronomy'],
            ['slug'=>'astronomy/indian-seasons','title'=>'Indian Seasons','template'=>'astronomy'],
            ['slug'=>'astronomy/vernal-equinox','title'=>'Vernal Equinox','template'=>'astronomy'],
            ['slug'=>'astronomy/summer-solstice','title'=>'Summer Solstice','template'=>'astronomy'],
            ['slug'=>'astronomy/autumnal-equinox','title'=>'Autumnal Equinox','template'=>'astronomy'],
            ['slug'=>'astronomy/winter-solstice','title'=>'Winter Solstice','template'=>'astronomy'],
            ['slug'=>'planets/sidereal-zodiac','title'=>'Sidereal Zodiac','template'=>'article'],
            ['slug'=>'planets/tropical-zodiac','title'=>'Tropical Zodiac','template'=>'article'],
        ]
    ],
    'devotion' => [
        'title' => 'Devotion',
        'icon' => 'ॐ',
        'description' => 'Aarti, Chalisa, Stotram, Mantra and devotional reading collections.',
        'pages' => [
            ['slug'=>'devotion/aarti','title'=>'Aarti Collection','template'=>'devotion'],
            ['slug'=>'devotion/chalisa','title'=>'Chalisa Collection','template'=>'devotion'],
            ['slug'=>'devotion/stotram','title'=>'Stotram Collection','template'=>'devotion'],
            ['slug'=>'devotion/mantra','title'=>'Vedic Mantra','template'=>'devotion'],
            ['slug'=>'devotion/namavali','title'=>'Deities Namavali','template'=>'devotion'],
            ['slug'=>'devotion/durga-saptashati','title'=>'Durga Saptashati','template'=>'devotion'],
            ['slug'=>'devotion/marathi-aarti','title'=>'Marathi Aartis','template'=>'devotion'],
            ['slug'=>'devotion/ashtakam','title'=>'Ashtakam Collection','template'=>'devotion'],
            ['slug'=>'devotion/shatkam','title'=>'Shatkam','template'=>'devotion'],
            ['slug'=>'devotion/kavacham','title'=>'Kavacham','template'=>'devotion'],
            ['slug'=>'devotion/sundarkand','title'=>'Sundarkand','template'=>'devotion'],
            ['slug'=>'devotion/hanuman-bahuk','title'=>'Hanuman Bahuk','template'=>'devotion'],
            ['slug'=>'devotion/nama-ramayanam','title'=>'Nama Ramayanam','template'=>'devotion'],
            ['slug'=>'devotion/eka-shloki-ramayana','title'=>'Eka Shloki Ramayana','template'=>'devotion'],
            ['slug'=>'devotion/yantra','title'=>'Vedic Yantra','template'=>'collection'],
            ['slug'=>'devotion/gods/ashta-vinayaka','title'=>'Ashta Vinayaka','template'=>'article'],
            ['slug'=>'devotion/gods/lord-vishnu','title'=>'Lord Vishnu','template'=>'article'],
            ['slug'=>'devotion/gods/navagraha','title'=>'Navagraha','template'=>'article'],
            ['slug'=>'devotion/gods/lord-kubera','title'=>'Lord Kubera','template'=>'article'],
            ['slug'=>'devotion/gods/lord-ganesha','title'=>'Lord Ganesha','template'=>'article'],
            ['slug'=>'devotion/gods/lord-shiva','title'=>'Lord Shiva','template'=>'article'],
            ['slug'=>'devotion/goddesses/mahalakshmi','title'=>'Maha Lakshmi','template'=>'article'],
            ['slug'=>'devotion/goddesses/ashta-lakshmi','title'=>'Ashta Lakshmi','template'=>'article'],
            ['slug'=>'devotion/goddesses/dasha-mahavidya','title'=>'Dasha Mahavidya','template'=>'article'],
            ['slug'=>'devotion/goddesses/saraswati','title'=>'Saraswati','template'=>'article'],
            ['slug'=>'devotion/goddesses/gayatri','title'=>'Gayatri','template'=>'article'],
            ['slug'=>'devotion/mantra/mahalakshmi','title'=>'Mahalakshmi Mantras','template'=>'devotion'],
            ['slug'=>'devotion/mantra/diwali','title'=>'Diwali Mantras','template'=>'devotion'],
            ['slug'=>'devotion/mantra/ganesha','title'=>'Shri Ganesha Mantra','template'=>'devotion'],
            ['slug'=>'devotion/mantra/gayatri','title'=>'Gayatri Mantra','template'=>'devotion'],
            ['slug'=>'devotion/mantra/shanti-path','title'=>'Shanti Path','template'=>'devotion'],
            ['slug'=>'devotion/yantra/puja','title'=>'Yantra Puja Vidhi','template'=>'article'],
            ['slug'=>'devotion/yantra/lakshmi-ganesha','title'=>'Lakshmi Ganesha Yantra','template'=>'article'],
            ['slug'=>'devotion/yantra/ganesha','title'=>'Shri Ganesha Yantra','template'=>'article'],
            ['slug'=>'devotion/yantra/kubera','title'=>'Kubera Yantra','template'=>'article'],
            ['slug'=>'devotion/yantra/mahavidya','title'=>'Mahavidya Yantra','template'=>'article'],
            ['slug'=>'devotion/rituals/kumbha-mela','title'=>'Kumbha Mela','template'=>'article'],
            ['slug'=>'devotion/rituals/shraddha-karma','title'=>'Shraddha Karma','template'=>'article'],
            ['slug'=>'devotion/rituals/vivah-sanskar','title'=>'Vivah Sanskar','template'=>'article'],
            ['slug'=>'devotion/rituals/upakarma','title'=>'Upakarma','template'=>'article'],
            ['slug'=>'devotion/rituals/namakarana','title'=>'Namakarana Samskara','template'=>'article'],
        ]
    ],
    'gallery' => [
        'title' => 'Gallery',
        'icon' => '◇',
        'description' => 'Visual collections for festivals, devotional art and traditional design.',
        'pages' => [
            ['slug'=>'gallery/rangoli','title'=>'Rangoli Collection','template'=>'gallery'],
            ['slug'=>'gallery/greetings','title'=>'Festival Greetings','template'=>'gallery'],
            ['slug'=>'gallery/mehandi','title'=>'Mehandi Collection','template'=>'gallery'],
            ['slug'=>'gallery/hindu-festivals','title'=>'Hindu Festival Gallery','template'=>'gallery'],
            ['slug'=>'gallery/indian-festivals','title'=>'Indian Festival Gallery','template'=>'gallery'],
            ['slug'=>'gallery/krishna-miniature','title'=>'Krishna Miniature','template'=>'gallery'],
            ['slug'=>'gallery/bal-krishna','title'=>'Bal Krishna','template'=>'gallery'],
            ['slug'=>'gallery/bal-hanuman','title'=>'Bal Hanuman','template'=>'gallery'],
            ['slug'=>'gallery/bal-ganesha','title'=>'Bal Ganesha','template'=>'gallery'],
            ['slug'=>'gallery/hindu-symbols','title'=>'Hindu Symbols','template'=>'gallery'],
            ['slug'=>'gallery/oil-paintings','title'=>'Oil Paintings','template'=>'gallery'],
        ]
    ],
    'learn' => [
        'title' => 'Learn',
        'icon' => '◫',
        'description' => 'Tutorials and explanatory content for Panchang, Muhurat and Vedic calendar concepts.',
        'pages' => [
            ['slug'=>'learn/tutorials','title'=>'Tutorials','template'=>'collection'],
            ['slug'=>'learn/panchang','title'=>'Understanding Panchang','template'=>'article'],
            ['slug'=>'learn/choghadiya','title'=>'Understanding Choghadiya','template'=>'article'],
            ['slug'=>'learn/muhurat','title'=>'Understanding Muhurat','template'=>'article'],
            ['slug'=>'learn/nakshatra','title'=>'Understanding Nakshatra','template'=>'article'],
            ['slug'=>'learn/rahu-kala','title'=>'Understanding Rahu Kala','template'=>'article'],
            ['slug'=>'learn/faq','title'=>'FAQ','template'=>'article'],
            ['slug'=>'learn/contact','title'=>'Contact','template'=>'article'],
            ['slug'=>'learn/apps','title'=>'Mobile Apps','template'=>'collection'],
            ['slug'=>'learn/wallpapers','title'=>'Mobile Wallpapers','template'=>'gallery'],
        ]
    ],
];
